version: "3.5"

services:

  frontend:
    container_name: "frontend"
    restart: always
    env_file: ./frontend/.env
    build:
      context: ./frontend
    volumes:
      - ./playbooks:/playbooks:ro
    ports:
      - "80:3000"
    networks:
      - web
