version: "3.5"

services:

  frontend:
    container_name: "frontend"
    restart: always
    build:
      context: ./frontend
    ports:
      - "80:3000"

  backend:
    container_name: "backend"
    restart: always
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/playbooks:/usr/src/app/playbooks
    networks:
      - db

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=clustertools
      - MONGO_INITDB_ROOT_PASSWORD=clust3r
    networks:
      - db

networks:
  db:
    driver: bridge
